tasks ids are too similar
openzim/zimfarm pull request #566
Opened 2020-11-29 16:29 UTC by mahakporwal02

## Rationale

[//]: # (Briefly explain the reason behind this change.)
Task ids were too similar hence difficult to differentiate

#304 
## Changes
I have reversed the task ids as suggested and the made the first five characters as short id which makes it more convinient

2020-11-29 16:35 UTC, mahakporwal02 commented
@kelson @rgaudin ![Screenshot from 2020-11-29 22-02-39](https://user-images.githubusercontent.com/56486682/100547799-b6e2e500-328e-11eb-8aeb-cd67ba5b516e.png)
Now they are fairly randomised
![Screenshot from 2020-11-29 22-04-31](https://user-images.githubusercontent.com/56486682/100547828-e4c82980-328e-11eb-9a4d-adabeb4996fa.png)
Short ids are the first 5 characters

2020-11-30 08:47 UTC, rgaudin requested changes
Looks good! Please fix the minor formatting stuff.

2020-11-30 08:47 UTC, rgaudin commented on dispatcher/backend/src/utils/scheduling.py
> +        "_id": ObjectId(str(ObjectId())[::-1])
We need a comment here.

2020-11-30 08:47 UTC, rgaudin commented on dispatcher/frontend-ui/src/constants.js
> +  return id.substr(0,5);
code formatting: space after comma.

2020-12-01 09:18 UTC, rgaudin commented
@mahakporwal02 once you're done with your changes, ensure your code passes the tests (reports auto-included in the PR) and then re-request a review.

2020-12-01 13:01 UTC, mahakporwal02 commented
@rgaudin Sorry I force pushed a commit because I was unable to push the last commit due to some mistakes I made online in my personal repository

2020-12-01 13:48 UTC, rgaudin approved these changes
:+1 thanks

2020-12-01 13:48 UTC, merged

2020-12-01 13:49 UTC, rgaudin commented
Oh and you should link the issue you fix using the right panel of the PR. That way, it will be closed automatically on merge