SSH key upload via UI
openzim/zimfarm pull request #600
Opened 2021-01-08 13:13 UTC by mahakporwal02

## Rationale

[//]: # (Briefly explain the reason behind this change.)
Easier to upload SSH key via UI

#363 
## Changes
Changed permissions for adding ssh keys and create  UI in edit tab in updateUser

2021-01-08 13:32 UTC, mahakporwal02 commented
![Screenshot from 2021-01-08 18-59-20](https://user-images.githubusercontent.com/56486682/104020748-b1f54780-51e3-11eb-905c-bd61bfc73377.png)
![Screenshot from 2021-01-08 18-59-32](https://user-images.githubusercontent.com/56486682/104020761-b6b9fb80-51e3-11eb-86ed-f48792dd859f.png)
@rgaudin When I am applying black formatting to init.py the spaces in `permission=""` disappears
So should I add them anyways?

2021-01-08 13:58 UTC, rgaudin commented
@kelson42 are you happy with the depicted workflow? Or would you prefer it to upload the RSA public key file directly?

2021-01-08 14:24 UTC, kelson42 commented
@rgaudin @mahakporwal02 I think this is good but:
* it should be a textarea (big enough so the user can somehow look to what he has copy/paste)
* A filter should be done to remove the carriage returns that a cut and paste might have introduced
* The result should be checked if it looks good, otherwise if will just fail later and the user will ask why

2021-01-11 14:00 UTC, mahakporwal02 commented
![Screenshot from 2021-01-11 19-28-00](https://user-images.githubusercontent.com/56486682/104191355-6b058d00-5443-11eb-93f9-cecdcb438a57.png)

2021-01-11 14:35 UTC, mahakporwal02 commented
![Screenshot from 2021-01-11 20-05-01](https://user-images.githubusercontent.com/56486682/104195215-54ae0000-5448-11eb-9fbc-4f8d8781f80f.png)

2021-01-15 08:19 UTC, kelson42 commented
@mahakporwal02 Do you expect new review from us now?

2021-01-15 08:49 UTC, mahakporwal02 commented
@kelson42 @rgaudin Yes, I expect a review

2021-01-15 10:50 UTC, kelson42 commented
@mahakporwal02 From the UI point-of-view it looks good. Thx!

2021-01-15 11:30 UTC, rgaudin requested changes
Thanks for this. There are a number of small issues, mostly formatting and preciseness.
I am pushing a fix for those but please take a moment to understand those minor mistakes.

2021-01-15 11:30 UTC, rgaudin commented on dispatcher/frontend-ui/src/components/UpdateUser.vue
> +        key: null,
None of those declared vars are used anyway…

2021-01-15 11:30 UTC, rgaudin commented on dispatcher/frontend-ui/src/components/UpdateUser.vue
> +        parent.working = true;
Why not using similar code as for updating user? Using a parent.error seems unnecessary

2021-01-15 11:30 UTC, rgaudin commented on dispatcher/frontend-ui/src/components/UpdateUser.vue
> +        const payload = {name: parent.form.keyName, key: key};
You're not testing what you send here ; you can send empty values

2021-01-15 11:30 UTC, rgaudin commented on dispatcher/frontend-ui/src/components/UpdateUser.vue
> +              parent.$router.back();  // redirect
Why going back? Just redirect to the user's profile or users list

2021-01-15 11:30 UTC, rgaudin commented on dispatcher/frontend-ui/src/views/UserView.vue
> +        <table v-if="user.ssh_keys.length" class="table table-sm table-striped table-in-tab">
broke the display of user profile for users without SSH keys (most of them)

2021-01-15 11:30 UTC, rgaudin commented on dispatcher/frontend-ui/src/components/UpdateUser.vue
> +      <label class="mr-2" for="cu_password">Add SSH Key</label>
label assigned to wrong element

2021-01-15 11:35 UTC, rgaudin approved these changes

2021-01-15 11:36 UTC, merged