Add freecodecamp scraper
openzim/zimfarm pull request #815
Opened 2023-08-29 14:38 UTC by benoit74

## Rationale

- Fix #804 
- small fix to openAPI specification

## Changes

- dispatcher/backend: freecodecamp has been added to the `ScheduleCategory` and `Offliner` enums
- dispatcher/backend: `DockerImageName` for freecodecamp has been set to `openzim/freecodecamp`
- dispatcher/backend: freecodecamp flags schema has been defined
- dispatcher/backend: freecodecamp output location has been defined
- dispatcher/frontend-ui: freecodecamp has been added to `categories`, `warehouse_paths` and `offliners` in `src/contstants.js`
- openAPI specification has been adapted to reflect the fact that `POST /tasks/{task_id}` operation needs a `worker_name` set as query parameter

## Tests
- a recipe for freecodecamp has been created successfully locally, flags have been set ; the recipe has not been requested / ran by any worker locally
- openAPI spec adaptation has been tested locally with success

2023-08-30 11:25 UTC, rgaudin requested changes
Good ; thanks for the test, it's nice to have.
I am requesting changes mostly because of the category/warehouse_path that @kelson42 must answer first.
If you can make a minor release about `output` param, that would be nice as this is a new scraper.

2023-08-30 11:25 UTC, rgaudin commented on dispatcher/frontend-ui/src/constants.js
> +  warehouse_paths: ["/freecodecamp", "/gutenberg", "/ifixit", "/other", "/phet", "/psiram", "/stack_exchange",
Also for @kelson42 to decide on but I believe those FCC ZIMs will fall under `other` given there's gonna be only one for now. I don't think it matches `mooc` either.

2023-08-30 11:25 UTC, rgaudin commented on dispatcher/backend/src/common/schemas/offliners/freecodecamp.py
> +            "description": "Language of zim file and curriculum",
Can you provide a static list here? Content people would not know

2023-08-31 07:08 UTC, benoit74 commented on dispatcher/backend/src/utils/offliners.py
> +    Offliner.freecodecamp: od("fcc2zim", "output-dir", False),
Done, 1.1.0 has been released

2023-08-31 07:16 UTC, kelson42 commented
> I am requesting changes mostly because of the category/warehouse_path that @kelson42 must answer first.

I guess I missed the question, sorry. But if the question is: do we need a dedicated (zimfarm) catwgory, IMHO yes.

2023-08-31 13:12 UTC, benoit74 commented
There is a reason why the output flag is kept in each scraper flags ; it is "mandatory" to avoid the UI / API having mixed feeling about this weird flag. I reverted the change.

2023-08-31 13:27 UTC, merged