Missing cancel requester
openzim/zimfarm pull request #831
Opened 2023-09-26 15:02 UTC by benoit74

## Rationale

Fix #814 

## Changes
- fix logic to set `canceled_by` property when the `cancel` event is received and this property was not already set by a cancel requester
- fix UI to show `canceled_by` property on the `cancel_requested`event when the cancellation is not yet effective (otherwise the property is not visible until the cancellation is effective, even if present in the API)
- fix a misleading variable named `reserved_by` instead of `canceled_by` in `utils.py`

2023-09-26 15:04 UTC, benoit74 commented
Draft because based on `missing_schedule_name` branch which is waiting to be reviewed/merged

2023-09-28 11:30 UTC, rgaudin requested changes
Thank you for the annoying simulation of this in the test 👍 
Please add a few comments as suggested inline. This will greatly help future us I predict 😉

2023-09-28 11:30 UTC, rgaudin commented on dispatcher/backend/src/tests/integration/routes/business_logic/test_task_cancel_bl.py
> +        assert response.json["canceled_by"] == username
This mandates a comment explaining why the canceled_by isn't applied.

2023-09-28 11:30 UTC, rgaudin commented on dispatcher/backend/src/tests/integration/routes/business_logic/test_task_cancel_bl.py
> +        assert response.json["canceled_by"] == username
This calls for a comment reminding that client's cancel has access_token built for `username`

2023-09-28 11:30 UTC, rgaudin commented on dispatcher/backend/src/tests/integration/routes/business_logic/test_task_cancel_bl.py
> +        CANCELED_BY = "bob"
Why the uppercase?

2023-09-28 11:30 UTC, rgaudin commented on dispatcher/backend/src/tests/integration/routes/business_logic/test_task_cancel_bl.py
> +        assert response.json["canceled_by"] == CANCELED_BY
Opposite comment here explaining why in this case it's applied

2023-09-28 14:09 UTC, merged